# Generated by Django 4.2.4 on 2023-09-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=300)),
                ('phone', models.IntegerField()),
                ('name_cake', models.CharField(max_length=100)),
                ('category_cake', models.CharField(max_length=100)),
                ('name_filling', models.CharField(max_length=100)),
                ('size_cake', models.CharField(max_length=100)),
                ('wish', models.TextField()),
                ('update', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
