# Generated by Django 4.2.4 on 2023-09-10 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0002_rename_first_name_purchase_адреса_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='category_cake',
            new_name='Категорія',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='name_cake',
            new_name='Назва_торта',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='name_filling',
            new_name='Начинка',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='wish',
            new_name='Побажання',
        ),
        migrations.RenameField(
            model_name='purchase',
            old_name='size_cake',
            new_name='Розмір',
        ),
    ]
