# Generated by Django 4.2.4 on 2023-09-10 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_rename_category_cake_purchase_категорія_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='Категорія',
            field=models.CharField(choices=[('Торти на день народження', 'the a birthday'), ('Дитячі торти', 'kids'), ('Весільні торти', 'wedding'), ('Корпоративні торти', 'corporate')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='Начинка',
            field=models.CharField(default='', max_length=100),
        ),
    ]
