# Generated by Django 4.2.4 on 2023-09-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0004_alter_purchase_категорія_alter_purchase_начинка'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='Розмір',
            new_name='Вага',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='Категорія',
            field=models.CharField(choices=[('Торти на день народження', 'Торти на день народження'), ('Дитячі торти', 'Дитячі торти'), ('Весільні торти', 'Весільні торти'), ('Корпоративні торти', 'Корпоративні торти')], default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='Начинка',
            field=models.CharField(choices=[('Червоний оксамит із полуницею', 'Червоний оксамит із полуницею'), ('Манго-маракуйя', 'Манго-маракуйя'), ('Лавандовий', 'Лавандовий'), ('Карамельний', 'Карамельний'), ('Фісташковий з малиною', 'Фісташковий з малиною'), ('Подвійний шоколад з вишневим фламбе', 'Подвійний шоколад з вишневим фламбе')], default='', max_length=100),
        ),
    ]
