# Generated by Django 4.2.4 on 2023-08-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('min_size', models.CharField(max_length=30)),
            ],
        ),
    ]
