# Generated by Django 4.2.4 on 2023-08-30 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0002_alter_info_options_info_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='type',
            field=models.CharField(choices=[('Торти на день народження', 'the a birthday'), ('Дитячі торти', 'kids'), ('Весільні торти', 'wedding'), ('Корпоративні торти', 'corporate')], default='', max_length=30),
        ),
    ]
