# Generated by Django 4.2.4 on 2023-09-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0003_info_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='type',
            field=models.CharField(choices=[('Торти на день народження', 'the a birthday'), ('Дитячі торти', 'kids'), ('Весільні торти', 'wedding'), ('Корпоративні торти', 'corporate'), ('Дитячі торти 2', 'kids2'), ('Дитячі торти 3', 'kids3')], default='', max_length=30),
        ),
    ]
