# Generated by Django 4.2.4 on 2023-09-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cake', '0010_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='type',
            field=models.CharField(choices=[('Торти на день народження', 'the a birthday'), ('Дитячі торти', 'kids'), ('Весільні торти', 'wedding'), ('Корпоративні торти', 'corporate')], default='', max_length=30),
        ),
    ]
